---
- name: Fail when homedir_user or homedir_result are unset
  fail:
    msg: You have to set homedir_user and homedir_result
  when: (not homedir_user) or (not homedir_result)

- name: Figure out the user's home dir
  getent:
    database: passwd
    key: "{{ homedir_user }}"
    fail_key: true

- name: Fail when no home directory found
  fail:
    msg: "No home directory found for user '{{ homedir_user }}'"
  when: not getent_passwd[homedir_user][4]

- name: Set requested variable
  set_fact:
    {"{{ homedir_result }}": "{{ getent_passwd[homedir_user][4] }}"}
