---
- name: Converge
  hosts: all
  roles:
    - role: homedir
      vars:
        homedir_user: root
        homedir_result: root_homedir
    - role: homedir
      vars:
        homedir_user: test
        homedir_result: test_homedir
  post_tasks:
    - name: Verify that the output is correct
      assert:
        that:
          - "'{{ root_homedir }}' == '/root'"
          - "'{{ test_homedir }}' == '/home/test'"
